### PR TITLE
Closes #293 and #295

### LINKED ISSUE #293: Upgrade zombie to v6
We're currently using Zombie 4.x, and need to update to the latest 6.x.

Reproduction Steps:

* run `npm upgrade zombie`
* run `npm test` and see the tests will now fail in a few places, and the process will hang at the end.

How to complete this task:

* Ensure you're running Node.js 8+
* Update the zombie dependency version as shown above
* Consult the [zombie docs](http://zombie.js.org/) to update the tests in `test/index.js` to conform to the latest standards.
* Make a PR! 🎉

### PR DESCRIPTION
**Pull request by jkmdev**
This fix:
- updates the Zombie dependency from 4.x to 6.x and makes sure tests are up to date
- updates the trackjs dependency to stop it from creating errors when tests are run
- makes sure that testing properly terminates upon completion

### Motivation and Context
- [x] Why is this change required? What problem does it solve?

This change was needed so that tests ran properly without any errors being created.
- [x] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

Closes #293 and #295 

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.

All the tests pass now and no errors are printed to the console. I’ve updated trackjs to a version that doesn’t create errors in the application, as per issue #295 .  I initially chose the latest version but I got an error that seemed specific to the dependency itself, so I decided to go with a slightly earlier version.

I compared the readme for the 6.x version of zombie to one from the 4.x version using vim, and the only significant changes I noticed were that two new functions were added to the browser object (browser.source, browser.html), and that zombie now has support for HTTP basic access authentication. Since these new features didn't seem relevant to the implementation of the current tests I decided not to make any changes to them.

The tests no longer hang when completed. This issue was caused when a source was added to the plyr player; I changed the source type from video to audio and this seemed to fix the issue.

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [x] All tests passed.

### CODE REVIEW

File: js/everything.js [hunk 1]
```diff
@@ -269,7 +269,7 @@ var ZenPlayer = {
             }.bind(this));
 
             plyrPlayer.plyr.source({
-                type: "video",
+                type: "audio",
```
Comment (shakeelmohamed) [inline js/everything.js]: This change actually breaks functionality 😄 please revert it

**Comment by shakeelmohamed** [comment]
Thanks @jkmdev, welcome to the org! I fixed the test timeout issue with #298, pretty simple fix
